// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package types

type LoginResponse struct {
	UserId int64  `json:"userId"`
	Token  string `json:"token"`
}

type MobileLoginRequest struct {
	Mobile           string `json:"mobile"`
	VerificationCode string `json:"verificationCode"`
}

type RegisterRequest struct {
	Username         string `json:"username"`
	Mobile           string `json:"mobile"`
	Password         string `json:"password"`
	VerificationCode string `json:"verificationCode"`
}

type RegisterResponse struct {
	UserId int64  `json:"userId"`
	Token  string `json:"token"`
}

type UserInfoResponse struct {
	UserId   int64  `json:"userId"`
	Username string `json:"username"`
	Avatar   string `json:"avatar"`
}

type UserInfoUpdateRequest struct {
	Username string `json:"username" optional`
	Passwrod string `json:"password"`
	Mobile   string `json:"mobile"`
	Avatar   string `json:"avatar"`
}

type UsernameLoginRequest struct {
	Username string
	Password string
}

type VerificationRequest struct {
	Mobile string `json:"mobile"`
}

type VerificationResponse struct {
}
