server:
  port: 8090
spring:
  application:
    name: ai
  cloud:
    consul:
      host: 192.168.200.138
      port: 8500
      discovery:
        service-name: ${spring.application.name}
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: deepseek-r1:1.5b       # 与本地模型名称对应
  datasource:
    url: jdbc:postgresql://192.168.200.138:5432/postgres
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
mybatis-plus:
  type-aliases-package: com.code.commen.pojo
  global-config:
    db-config:
      id-type: auto # 全局主键策略，auto表示数据库ID自增

