// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2
// Source: user.proto

package server

import (
	"context"

	"go-zhihu/application/user/internal/logic"
	"go-zhihu/application/user/internal/svc"
	"go-zhihu/application/user/service"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	service.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Register(ctx context.Context, in *service.RegisterRequest) (*service.RegisterResponse, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserServer) FindById(ctx context.Context, in *service.FindByIdRequest) (*service.FindByIdResponse, error) {
	l := logic.NewFindByIdLogic(ctx, s.svcCtx)
	return l.FindById(in)
}

func (s *UserServer) FindByMobile(ctx context.Context, in *service.FindByMobileRequest) (*service.FindByMobileResponse, error) {
	l := logic.NewFindByMobileLogic(ctx, s.svcCtx)
	return l.FindByMobile(in)
}

func (s *UserServer) SendSms(ctx context.Context, in *service.SendSmsRequest) (*service.SendSmsResponse, error) {
	l := logic.NewSendSmsLogic(ctx, s.svcCtx)
	return l.SendSms(in)
}

func (s *UserServer) MobileLogin(ctx context.Context, in *service.MobileLoginRequest) (*service.LoginResponse, error) {
	l := logic.NewMobileLoginLogic(ctx, s.svcCtx)
	return l.MobileLogin(in)
}

func (s *UserServer) UsernameLogin(ctx context.Context, in *service.UsernameLoginRequest) (*service.LoginResponse, error) {
	l := logic.NewUsernameLoginLogic(ctx, s.svcCtx)
	return l.UsernameLogin(in)
}

func (s *UserServer) UserInfoUpdate(ctx context.Context, in *service.UserInfoUpdateRequest) (*service.LoginResponse, error) {
	l := logic.NewUserInfoUpdateLogic(ctx, s.svcCtx)
	return l.UserInfoUpdate(in)
}
